export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as FindMe } from './FindMe'
export { default as About } from './About'
export { default as Education } from './Education'
export { default as WorkExperience } from './WorkExperience'
export { default as AnimateBg } from './AnimateBg'
export { default as Footer } from './Footer'
